version: '3.9'
services:
  my-sql:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple_data
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./data/mysql:/var/lib/mysql
